// src/screens/shared/PrivacySecurityScreen.js
// Shared privacy & security information screen accessible from all profile screens.

import React from 'react';
import {
  View, Text, ScrollView, TouchableOpacity, StyleSheet,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons }          from '@expo/vector-icons';

import {
  COLORS, GLASS, FONTS, TYPE, SPACING, RADIUS,
} from '../../theme';

function Section({ title, children }) {
  return (
    <View style={[GLASS.standard, styles.card]}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function Item({ text }) {
  return (
    <View style={styles.item}>
      <View style={styles.bullet} />
      <Text style={[TYPE.body, { flex: 1, lineHeight: 22 }]}>{text}</Text>
    </View>
  );
}

export default function PrivacySecurityScreen({ navigation }) {
  const insets = useSafeAreaInsets();

  return (
    <View style={{ flex: 1 }}>
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{
          paddingTop:    insets.top + SPACING.sm,
          paddingBottom: insets.bottom + SPACING.xxl,
        }}
      >
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
            <Ionicons name="chevron-back" size={24} color={COLORS.textPrimary} />
          </TouchableOpacity>
          <Text style={[TYPE.h1, { flex: 1 }]}>Privacy & Security</Text>
        </View>

        <View style={{ paddingHorizontal: SPACING.lg, gap: SPACING.lg }}>

          <Section title="Data We Collect">
            <Item text="Your full name and email address provided during registration." />
            <Item text="Your school name and grade level (learners only)." />
            <Item text="Your learning progress — which projects you enrolled in and completed." />
            <Item text="Step submission photos you choose to upload as proof of completion." />
            <Item text="XP, level, and achievement data generated by your activity in the app." />
          </Section>

          <Section title="How Your Data Is Stored">
            <Item text="All data is stored securely on Supabase — a cloud database platform with enterprise-grade encryption at rest and in transit (TLS 1.2+)." />
            <Item text="Passwords are never stored in the app. Authentication is managed entirely by Supabase Auth." />
            <Item text="Step photos are stored in Supabase Storage with private access policies." />
            <Item text="Your data is hosted in Singapore-region servers." />
          </Section>

          <Section title="Your Rights">
            <Item text="You may request a copy of your personal data at any time." />
            <Item text="You may request deletion of your account and all associated data using the Delete Account option in your Profile settings." />
            <Item text="Your data is never sold to third parties." />
            <Item text="S-MIB does not use your data for advertising purposes." />
          </Section>

          <Section title="Contact Us">
            <Text style={[TYPE.body, { lineHeight: 22 }]}>
              For privacy questions or data requests, contact the S-MIB team at:
            </Text>
            <Text style={[styles.email]}>smib.support@uts.edu.my</Text>
          </Section>

        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: SPACING.lg,
    paddingBottom:     SPACING.lg,
    gap:               SPACING.md,
  },
  backBtn: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius:    RADIUS.pill,
    padding:         SPACING.sm,
  },
  card: {
    borderRadius: RADIUS.lg,
    padding:      SPACING.lg,
    gap:          SPACING.sm,
  },
  sectionTitle: {
    fontFamily:   FONTS.heading800,
    fontSize:     16,
    color:        COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  item: {
    flexDirection: 'row',
    alignItems:    'flex-start',
    gap:           SPACING.sm,
  },
  bullet: {
    width:           6,
    height:          6,
    borderRadius:    RADIUS.pill,
    backgroundColor: COLORS.aiCyan,
    marginTop:       8,
    flexShrink:      0,
  },
  email: {
    fontFamily: FONTS.body700,
    fontSize:   14,
    color:      COLORS.aiCyan,
    marginTop:  SPACING.xs,
  },
});
